apiVersion: v1
kind: Template
metadata:
  name: soapserver
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: soapserver
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: soapserver
      template:
        metadata:
          labels:
            app: soapserver
        spec:
          containers:
            - name: soapserver
              #image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/soapserver:v1
              #image: quay.io/tquigly/soapstub:latest
              image: ${IMAGE}
              imagePullPolicy: Always
  - kind: Service
    apiVersion: v1
    metadata:
      name: soapserver
    spec:
      ports:
        - name: web
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: soapserver
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: soapserver
    spec:
      to:
        kind: Service
        name: soapserver
      port:
        targetPort: web
parameters:
  - name: PREFIX
  - name: NAMESPACE
  - name: IMAGE
